### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by remram44** [tibirna/qgit#106]
I would appreciate being able to change the date format, MM/DD/YYYY is very unnatural for me and hard to work with.

**Comment by tibirna** [comment]
Date format is controlled by your operating system settings. E.g. here it is mine: https://drive.google.com/file/d/1yrOzJCctzdyIHif_GebQdFCiZ8YFLm1o/view?usp=sharing

**Comment by remram44** [comment]
The ISO date format is not really a locale, and I don't think making the user change his locale system-wide (which will include desktop widgets and status bar, as well as calendar apps) is a solution. In this case I suppose it would even have to be a custom locale (ISO is not a locale!)

I will also point out that Git itself allows changing date formats. That includes the `log.date` option, that will change dates shown throughout Git commands (e.g. `git log`, `git show`), but not qgit.

Your call of course, I will respect a WONTFIX.

**Comment by tibirna** [comment]
I understand your points. My stand on this, though, is that date and time format are two of those things that most users have a global preference for, un-related to the application they are displayed into.

If you don't find natural the MM/DD/YYYY format (I don't, either), then I'm pretty sure you don't want to let your OS configured to display it for you all over the place, as it currently obviously has to do now, given that qgit picks it up.

As a corollary, if date and time format are a global preference (as I am convinced), forcing the user to configure them for each particular application is rude.

I also agree that the LC system as functional today is a bit quirky (e.g. forcing me to use en_SE or en_DK for date only, while using my default en_* for everything else). If I understand correctly, this is what makes you say the ISO date is not a locale (you need to scan the LC specifications to find one that displays _like_ the ISO standard requires).

Again, it's not a question of technical nature, it's a question of UX principle.

I will continue to ponder on the question.

Thanks!

**Comment by triffid** [comment]
Apparently [Qt makes it rather difficult to change the short date format](https://unix.stackexchange.com/a/420065), and `qgit` is the only place that I actually see Qt's short date format in use..
