### ISSUE TITLE
Show branch name in window header bar

### ISSUE THREAD

**Issue by ursjoss** [tibirna/qgit#107]
Currently (version 2.9), the window header bar of qgit displays the path of the repository.

It would be nice to also see the name of the branch there. This would come in especially handy when we open multiple branches in different instances of qgit to compare the history.

**Comment by tibirna** [comment]
Added. It will be avail in the next version (or in any compilation from the master branch, of course).

Remains to do:  when the HEAD is not a branch (like tags), display those instead (or perhaps an abbrev SHA) in the title

**Comment by ursjoss** [comment]
Ok, I understand, currently it just reads and displays `HEAD`. That somehow doesn't cover my use case yet, as I often launch two instances of qgit from the same git clone (same HEAD), but with different branches as parameters. Currently all instances would display the same branch in the title bar.
