### ISSUE TITLE
Clicking on individual commit in file view does not open the commit

### ISSUE THREAD

**Issue by t8m** [tibirna/qgit#11]
On Fedora 25 with qgit 2.7 clicking on individual commit in the file view (in the list of changes on that file) does not open the commit. The window with Rev list is opened but the revision opened is still the original one that was displayed in the Rev list before and not the desired revision.

Also rightclick on the commit in the file view does not open the contextual menu. This seems to be related to the problem above as both these problems started to appear in the same time. It seems to be some kind of race condition as on 2.6 the commit usually opened but sometimes not. In 2.7 the commit is never opened.

**Comment by tibirna** [comment]
I don't have a Fedora machine at hand and _my own tests can't reproduce this behaviour_. I'll get back after trying this on the distro-compiled Fedora 25 package.

**Comment by flok32** [comment]
I got the same issue after updating Xubuntu from 17.4 to 17.10
