### ISSUE TITLE
Show commit hash in Rev list

### ISSUE THREAD

**Issue by WickedSmoke** [tibirna/qgit#118]
Is there a way to show the commit hash in the Rev list?  I often want to identify a few commits by hash in the same historical area, but as these are not visible I must resort to clicking around on list items so that the hash gets displayed in the hash line edit widget.  A simple visual scan would be much easier.

**Comment by tibirna** [comment]
Thanks for your interest.

No, there is no SHA column currently. It was a design choice from the original author. In the meantime, displaying the SHA as integral part of the commit became more of a norm, so your request makes very much sense.

Thanks

**Comment by tibirna** [comment]
Implemented. Thanks!
