### ISSUE TITLE
Changing default terminal

### ISSUE THREAD

**Issue by bunyamintamar** [tibirna/qgit#126]
I want to be able to use gnome terminal instead of default terminal. Because the default terminal does not allow the user to type commands

**Comment by tibirna** [comment]
I'm not sure I understand. Please indicate which terminal you are refering to? Which part of the QGit UI should be replaced with the gnome terminal?

**Comment by bunyamintamar** [comment]
QGit's default terminal does not allow user input. I think it would be nice to be able to use an external terminal.

**Comment by SubOptimal** [comment]
@tibirna Following as demonstration

Assume you define an action as

```
read value
echo $value
```
The execution will stuck, as the QGit action window does not allow any user input.

@bunyamintamar A possible solution would be to use a GUI input dialog.

```
value=$(zenity --entry)
echo "the value is: ${value}"
```

![image](https://user-images.githubusercontent.com/653288/186350736-d0644f51-0b2c-4b77-867a-cb428adfe58a.png)

![image](https://user-images.githubusercontent.com/653288/186350761-61973bcb-2040-477e-bda5-e570cf9e56ce.png)

**Comment by tibirna** [comment]
@SubOptimal @bunyamintamar the 'Action' feature is not designed to be a full fledged shell interpreter. It is just meant to create simple scripts that are ran in a detached shell and then the output displayed in a text widget, which is not a terminal (it only reuses the desktop's standard terminal icon in the window title bar).

@bunyamintamar as described, the intention of 'Action' is not to provide a terminal, but you can actually start one by simply including it in an 'Action' script. You can choose whichever you want and I guess you could pass commands to it as indicated in that terminal's manual.

@SubOptimal to allow for edit boxes, follow the tip printed at the bottom of the 'Actions' dialog:
![image](https://user-images.githubusercontent.com/1239822/186438645-ef37e323-9690-43df-94a5-dcdf18a1088f.png)
Just include %lineedit:title=defaultvalue% at the appropriate place in your command. The input-ed value will replace the %..% token.

**Comment by SubOptimal** [comment]
@tibirna Thanks for the hint. I have not taken this into account. :facepalm:

To have a similar behavior like my zenity example. The following action code work as expected.

```
value="%lineedit:enter value=defaults%"
echo "the value is: ${value}"
```

Is there some other documentation about those features than [inputdialog.h#L9](https://github.com/tibirna/qgit/blob/master/src/inputdialog.h#L9)

**Comment by tibirna** [comment]
Minimal documentation exists in the QGit Handbook that you can access
from the 'Help' menu. That one displays the content of the README.adoc file
(of which you are already aware).

Thanks
Cristian

**Comment by bunyamintamar** [comment]
Thanks for the hint

**Comment by bunyamintamar** [comment]
Thanks for the hint
