### ISSUE TITLE
Ctrl+ to increase font does not work on Mint 20.3

### ISSUE THREAD

**Issue by dbu9** [tibirna/qgit#131]
Decreased the font and cannot get it back. 
![image](https://user-images.githubusercontent.com/118698819/229307523-4be1e9f9-b1a3-48bf-9a8e-13c94d00d133.png)
Control + does not work.

**Comment by wwestrop** [comment]
Try `Ctrl` `Shift` `+` instead

**Comment by dbu9** [comment]
Thanks. I think the help should be corrected:
![image](https://user-images.githubusercontent.com/118698819/229381818-501b901b-46e1-4d68-b777-6fc262a83815.png)

**Comment by wwestrop** [comment]
Perhaps, though I think it might be dependent on keyboard layout? e.g. on a UK layout, `+` and `=` share a key, so the `Ctrl`-`+` shortcut is "equivalent" to `Ctrl`-`Shift`-`=`. 

I agree that's not intuitive (I've seen this issue on Electron apps also), but don't know if changing it to `Ctrl`-`+` might also be confusing in some locales?
