### ISSUE TITLE
Add possibility to highlight all search results at once

### ISSUE THREAD

**Issue by zkrx** [tibirna/qgit#143]
It would be great if the embedded patch viewer had the possibility to highlight all matches from a search (with ctrl + f).

Browsers have this feature, most editors do it as well. When reviewing patches, highlighting all search results is a necessity. You hit ctrl + F, enter your keyword and then just scroll to quickly see all matches. Unfortunately, qgit doesn't do it by default (it  highlights one match at a time) and I wasn't able to find a setting to highlight all matches at once.

**Comment by tibirna** [comment]
Thanks for this request. It seems part of the work for this was done some time ago, but was not connected because of (at the time) slow performance on large patches. I mark this as an entry level issue.

**Comment by zkrx** [comment]
Wow that was very quick. I've just built and installed your latest release with cf3350e88cc8c8249385efac63ddf15ac1eff42a.patch applied and it seems to work fine. Thank you so much.

**Comment by tibirna** [comment]
Thank you for reporting the issue.
