### ISSUE TITLE
Salvaged from old home: Ctrl-C as a shortcut for Checkout is bad

### ISSUE THREAD

**Issue by tibirna** [tibirna/qgit#34]
Submitted by Andrey Rahmatullin on 2017-07-04.

Currently Ctrl-C is a shortcut for the Checkout dialog which is unexpected and inconvenient. Please replace with something else.

**Comment by negora** [comment]
I think it would be fantastic to have this problem fixed. Being able to input only 1 parameter prevents us to enjoy this powerful feature at 100%.

**Comment by negora** [comment]
I agree. Using `CTRL + C` for the checkout is not intuitive. We all are used to use that shortcut to copy.
