### ISSUE TITLE
The project information at OpenHub is outdated.

### ISSUE THREAD

**Issue by edson-a-soares** [tibirna/qgit#4]
I found this repository when I was looking for the bug track system for this project. I did it for Google, once links in https://www.openhub.net/p/qgit are either outdated or absent at all. Once there is a new site for the project, It would not be a bad idea update the project there. More contributors could find the project by means of that tool.

**Comment by tibirna** [comment]
Thanks Edson. I don't have any control over that entry in that aggregator. It's a pity, but in its 10+y history, qgit changed status fairly often and left a flaky trail in the internet.

**Comment by edson-a-soares** [comment]
I understand it.
Thanks for the feedback.
