### ISSUE TITLE
Rename README to README.adoc(?) to enable rendering on GitHub?

### ISSUE THREAD

**Issue by hartwork** [tibirna/qgit#73]
Hi!

Thanks a bunch for QGit! Since gitg keeps crashing on me to the point of not starting up at all for some repositories, QGit is a great thing to have, and its unique approach to visualization has turned out helpful a few times already — thanks!

I noticed that `README` uses special syntax but it's not rendered by GitHub due to lack of a file extension. It looks like reStructuredText to me. Are there reasons to *not* rename it to `README.rst` to keep rendering disabled?

Best, Sebastian

**Comment by tibirna** [comment]
Hello Sebastian

Warmest thanks for your very kind words.

Reason for not using .rst extension is majorly my ignorance. I might have known the reStructuredText notions some time ago, but I seem to not have noticed it in the README created by the original QGit author.

Thanks for noticing. I'll test and then proceed to the suggested modification.

Thanks
Cristian

**Comment by tibirna** [comment]
Upon trying my local installation of docutils' rst2html converter, I can see a rather large number of formating issues. So I will not proceed to the renaming for now, the raw text is still better readable than the rendering.

Thanks again

**Comment by hartwork** [comment]
Would you welcome a pull request fixing the syntax to be valid reStructuredText, Markdown, or AsciiDoc?

**Comment by tibirna** [comment]
Of course! Thanks in advance!

**Comment by hartwork** [comment]
Turns out it was supposed to be Asciidoc, not reStructuredText. Way better! Please check if #73 looks like the way forward.

**Comment by tibirna** [comment]
Merged. Thank you very much for the contribution!
