### ISSUE TITLE
make returns error on uic not found

### ISSUE THREAD

**Issue by Fabick75** [tibirna/qgit#94]
I've cloned latest release from the repository and tried to compile.
But when run make, they spit out these errors : 

> cd src/ && make -f Makefile 
make[1]: Entering directory '/home/user/Scaricati/source/qgit/src'
make -f Makefile.Release
make[2]: Entering directory '/home/user/Scaricati/source/qgit/src'
/usr/lib/x86_64-linux-gnu/qt4/bin/uic commit.ui -o ui_commit.h
make[2]: /usr/lib/x86_64-linux-gnu/qt4/bin/uic: Command not found
Makefile.Release:255: recipe for target 'ui_commit.h' failed
make[2]: *** [ui_commit.h] Error 127
make[2]: Leaving directory '/home/user/Scaricati/source/qgit/src'
Makefile:34: recipe for target 'release' failed
make[1]: *** [release] Error 2
make[1]: Leaving directory '/home/user/Scaricati/source/qgit/src'
Makefile:39: recipe for target 'sub-src-make_default' failed
make: *** [sub-src-make_default] Error 2

I'm on linux Mint 19 (Tara), with Plasma desktop and QT5. I've installed libQT4 v4.8.7 too, and QT5 v5.9.5 .

Thanks in advance for a reply

**Comment by tibirna** [comment]
Make sure your OS's development packages for Qt library are installed. This is personal setup issue outside of the scope of this issue recording system.
