### ISSUE TITLE
Git says "Under Linux, use ExitStatus to determine whether an external command failed"

### ISSUE THREAD

**Issue by brentr** [tibirna/qgit#95]
I'm a long time qgit fan.  Thank you for producing this wonderful, cross-platform, git GUI.
MyProcess::on_finished() has a comment that suggests that git status under Linux
returns with a non-zero exit code when there is no error, and, that is why you resort
read stderr to determine if a command failed.
My own tests, under Linux, show that "git status" returns with exit code 0.
I would suggest that you could resort to the STDERR hack only when the host OS is not Unix derived.

**Comment by tibirna** [comment]
Thanks for the good comments and for the suggestion. I will look into it.

(Any patches appreciated :-)

**Comment by tibirna** [comment]
Patch merged. Thanks!
